In [ ]:
import numpy as np

print('Задание на повторение материала.')

print('Задание 1.')

# Создать одномерный массив Numpy под названием a из 12 последовательных целых
# чисел чисел от 12 до 24 невключительно

a = np.linspace(12, 24, num=12, endpoint=False, retstep=False)
print('Массив\n', a)

Задание 1.
F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)
Значение расчетного коэффициента выше значения табличного, следовательно вид спорта оказывает статистически значимое влияние на рост спортсмена.


In [ ]:
print('Задание 2.')

# Создать 5 двумерных массивов разной формы из массива a. Не использовать в
# аргументах метода reshape число -1.

b = np.reshape(a, (2, 6))
c = np.reshape(a, (6, 2))
d = np.reshape(a, (2, 6), order='F')
e = np.reshape(a, (6, 2), order='F')
f = np.reshape(a, (2, 6), order='A')
print('Двумерные массивы без использования -1:\n', b)
print(c)
print(d)
print(e)
print(f)

In [ ]:
print('Задание 3.')

# Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах
# метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

b = np.reshape(a, (2, -1))
c = np.reshape(a, (6, -1))
d = np.reshape(a, (-1, 6), order='F')
e = np.reshape(a, (-1, 2), order='F')
f = np.reshape(a, (2, -1), order='A')
print('Двумерные массивы с использованием -1:\n', b)
print(c)
print(d)
print(e)
print(f)

In [ ]:
print('Задание 4.')

# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

g = np.reshape(a, (12, -1))
print('Массив одномерен:\n', g)

In [ ]:
print('Задание 5.')

# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей
# запятой из нормального распределения со средним, равным 0 и среднеквадратичным
# отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же
# атрибутом size, как и исходный массив.

o = np.linspace(-1, 1, num=12)
p = np.reshape(o, (3, 4))
print('Массив\n', p)
print('Среднее значение:', round(np.mean(p), 1))
print('Среднее квадратичное отклонение:', round(np.std(p)))
print('Одномерный массив\n', np.reshape(p, (12, 1)))

In [65]:
print('Задание 6.')

# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

a = np.arange(0, 20, 2)
print('Массив, убывающий от 20 до 0:\n', a[::-1])

Задание 6.
Массив, убывающий от 20 до 0
 [18 16 14 12 10  8  6  4  2  0]


In [67]:
print('Задание 7.')

# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих
# от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

b = np.arange(1, 20, 2)
print('В отличие от предыдущего массива, выделены все нечетные числа интервала:\n', b[::-1])

Задание 7.
В отличие от предыдущего массива, выделены все нечетные числа интервала
 [19 17 15 13 11  9  7  5  3  1]
Задание 8.
Задание 9.
Задание 10.
Задание 11.
Задание 12.
Задание 13.


In [77]:
print('Задание 8.')

# Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк
# которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего
# из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

a = np.array([(0, 0, 0), (0, 0, 0)])
b = np.array([(1, 1), (1, 1)])
c = np.hstack([a, b])
print('Массив\n', c)
print('Размер массива:', c.size)

Задание 8.
Массив
 [[0 0 0 1 1]
 [0 0 0 1 1]]
Размер массива: 10
Задание 9.
Задание 10.
Задание 11.
Задание 12.
Задание 13.


In [87]:
print('Задание 9.')

# Создать одномерный массив а, состоящий из последовательности целых чисел от 0
# до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив
# Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования
# матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного
# умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

a = np.arange(0, 12)
A = np.reshape(a, (4, 3))
At = A.transpose()
B = np.dot(A, At)
print('Размер матрицы А, умноженной на транспонированную матрицу А:', B.size)
print('Определитель матрицы В:', np.linalg.det(B), ', следовательно, обратной матрицы для нее не существует.')

Задание 9.
Размер матрицы А, умноженной на транспонированную матрицу А: 16
Определитель матрицы В: 0.0 , следовательно, обратной матрицы для нее не существует.
Задание 10.
Задание 11.
Задание 12.
Задание 13.


In [88]:
print('Задание 10.')

# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

np.random.seed(42)
print(np.random.rand(3))

Задание 10.
[0.37454012 0.95071431 0.73199394]
Задание 11.
Задание 12.
Задание 13.


In [89]:
print('Задание 11.')

# Создайте одномерный массив c, составленный из последовательности 16-ти случайных
# равномерно распределенных целых чисел от 0 до 16 невключительно. 

c = np.linspace(0, 16, num=16, endpoint=False, retstep=False)
print(c)

Задание 11.
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
Задание 12.
Задание 13.


In [96]:
print('Задание 12.')

# Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу
# D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной
# на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

C = np.reshape(c, (4, 4))
D = C + B * 10
print('Матрица\n', D)
print('Определитель матрицы D:', np.linalg.det(D), ', определитель равен нулю, поэтому вычисление обратной матрицы невозможно.')
print('Ранг матрицы D:', np.linalg.matrix_rank(D))

Задание 12.
Матрица
 [[  50.  141.  232.  323.]
 [ 144.  505.  866. 1227.]
 [ 238.  869. 1500. 2131.]
 [ 332. 1233. 2134. 3035.]]
Определитель матрицы D: 0.0 , определитель равен нулю, поэтому вычисление обратной матрицы невозможно.
Ранг матрицы D: 2
Задание 13.


In [99]:
print('Задание 13.')

# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
# Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции
# numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве
# источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для
# которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему
# элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент
# матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

D[D > 0] = 1
E = np.where(D > 0, B, C)
print('Полученная матрица\n', E)

Задание 13.
Полученная матрица
 [[  5.  14.  23.  32.]
 [ 14.  50.  86. 122.]
 [ 23.  86. 149. 212.]
 [ 32. 122. 212. 302.]]
